<table>
	<tbody>
		<tr>
			<td>id</td>
			<td>businessname</td>
			<td>street</td>
			<td>suite</td>
			<td>city</td>
			<td>state</td>
			<td>zip</td>
			<td>company_id</td>
			<td>phone</td>
			<td>contact</td>
			<td>segment</td>
		</tr>
		@foreach($company->locations as $location)
			<tr>  
			<td>{{$location->id}}</td>
			<td>{{$location->businessname}}</td>
			<td>{{$location->address->street}}</td>
			<td>{{$location->address->suite}}</td>
			<td>{{$location->address->city}}</td>
			<td>{{$location->address->state}}</td>
			<td>{{$location->address->zip}}</td>
			<td>{{$location->company_id}}</td>
			<td>{{$location->phone}}</td>
			<td>{{$location->contact}}</td>
			<td>{{$location->segment}}</td>
			</tr>
		@endforeach
	</tbody>
</table>